name: $(date:yyyyMMdd)$(rev:.rr) #20191209.00

trigger:
  - master

stages:
  - stage: compile
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: |
              dotnet build 3_devops/Devops.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test 3_devops/Devops.sln --logger trx --collect:"XPlat Code Coverage"
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: cobertura
              summaryFileLocation: '**/coverage.cobertura.xml'
  - stage: analyze
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.0.100'
          - script: dotnet tool install --global dotnet-sonarscanner
          - script: | 
              dotnet sonarscanner begin \
              /d:sonar.login=$SONAR_TOKEN \
              /d:sonar.host.url=https://sonarcloud.io/ \
              /d:sonar.cs.opencover.reportsPaths=**/TestResults/*/coverage.opencover.xml \
              /d:sonar.cs.vstest.reportsPaths=**/*.trx \
              /k:devops-jg1 \
              /o:jguillodev
              dotnet build 3_devops/Devops.sln
              dotnet test 3_devops/Devops.sln
              dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
            env:
              SONAR_TOKEN: $(SONAR_LOGIN) 
  - stage: pack
    jobs:
      - job:
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: docker image build -f 3_devops/dockerfile -t joshuaguillory/devops:$BUILD_NAME .
            env:
              BUILD_NAME: $(Build.DefinitionName)
          - script: docker login --username $DOCKER_USER --password $DOCKER_TOKEN
            env:
              DOCKER_TOKEN: $(DOCKER_TOKEN)
              DOCKER_USER: $(DOCKER_USER)
          - script: docker image push joshuaguillory/devops:$(BUILD_NAME)
              env:
                BUILD_NAME: $(Build.DefinitionName)

  